//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTSIDCReportService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REPORTDB : DbContext
    {
        public REPORTDB()
            : base("name=REPORTDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BATCH> BATCHES { get; set; }
        public virtual DbSet<CONFIGURATION> CONFIGURATIONS { get; set; }
        public virtual DbSet<FIELD> FIELDS { get; set; }
        public virtual DbSet<PAGE> PAGES { get; set; }
    }
}
