//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTSIDCReportService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELD
    {
        public int PK { get; set; }
        public string DOCID { get; set; }
        public string DOCTYPE { get; set; }
        public string FIELDNAME { get; set; }
        public string FIELDVALUE { get; set; }
        public string BATCH_INSTANCEID { get; set; }
        public string PATTERN { get; set; }
    }
}
