DECLARE @BatchId VARCHAR(50) = '{BATCHINSTANCEID}';

BEGIN
	DECLARE @TEMP TABLE (
		 batch_instanceid VARCHAR(150)
		,docid_p1 VARCHAR(150)
		,docid_p2 VARCHAR(150)
		,doctype_p1 VARCHAR(150)
		,doctype_p2 VARCHAR(150)
		,doc_conf_p1 VARCHAR(150)
		--,doc_conf_p2 VARCHAR(150)
		,conf_threshold_p1 VARCHAR(150)
		--,conf_threshold_p2 VARCHAR(150)
		,doctype1_pagecount int null
		,doctype2_pagecount int null
		)

	INSERT INTO @TEMP (batch_instanceid,docid_p1,docid_p2,doctype_p1,doctype_p2,doc_conf_p1,conf_threshold_p1)
	SELECT E.BATCH_INSTANCEID
		,E.DOCID
		,M.DOCID "DOCID_AV"
		,E.DOCTYPE
		,M.DOCTYPE "DOCTYPE_AV"
		,E.DOC_CONFIDENCE
		--,M.DOC_CONFIDENCE "DOC_CONFIDENCE_AV"
		,E.CONFIDENCE_THRESHOLD
		--,M.CONFIDENCE_THRESHOLD "CONFIDENCE_THRESHOLD_AV"
	FROM BATCHES B
	INNER JOIN PAGES E ON B.BATCH_INSTANCEID = E.BATCH_INSTANCEID
	INNER JOIN PAGES M ON B.BATCH_INSTANCEID = M.BATCH_INSTANCEID
		AND E.PAGEID = M.PAGEID
	WHERE B.BATCH_INSTANCEID = @BatchID
		AND B.STATUS IN (
			'FINISHED'
			,'READY_FOR_VALIDATION'
			)
		AND E.PATTERN LIKE '%DOCUMENT_ASSEMBLY%'
		AND M.PATTERN LIKE '%AUTOMATED_VALIDATION%'

	SELECT batch_instanceid, docid_p1, Count(*) DocCount 
		INTO #Doc_Count_p1 FROM @TEMP 
	WHERE BATCH_INSTANCEID = @BatchID
	GROUP BY batch_instanceid, docid_p1
	 
	SELECT batch_instanceid, docid_p2, Count(*) DocCount 
		INTO #Doc_Count_p2 FROM @TEMP 
	WHERE BATCH_INSTANCEID = @BatchID
	GROUP BY batch_instanceid, docid_p2

	UPDATE Page SET doctype1_pagecount = d1.DocCount FROM @TEMP page
		INNER JOIN #Doc_Count_p1 d1 ON d1.batch_instanceid = page.batch_instanceid and d1.docid_p1 = page.docid_p1 

	UPDATE page SET doctype2_pagecount = d2.DocCount FROM @TEMP page
		INNER JOIN #Doc_Count_p2 d2 ON d2.batch_instanceid = page.batch_instanceid and d2.docid_p2 = page.docid_p2 

	--SELECT * FROM @TEMP T ORDER BY T.doctype_p2

	DECLARE @DOCUMENTTYPES TABLE (DOCTYPE VARCHAR(500));

	INSERT INTO @DOCUMENTTYPES
	SELECT DISTINCT DOCTYPE
	FROM BATCHES B
		INNER JOIN PAGES P ON B.BATCH_INSTANCEID = P.BATCH_INSTANCEID
		LEFT JOIN IntellaLend_IDC_Service.DBO.[MTS.DocTypesWithoutSamples] S ON P.DOCTYPE = S.DocumentType
	WHERE B.BATCH_INSTANCEID = @BatchId
			AND P.PATTERN LIKE '%AUTOMATED_VALIDATION%'
			AND S.DOCUMENTTYPE IS NULL;

	--SELECT * FROM @DOCUMENTTYPES;

	WITH TABLE_T1
	AS (
		SELECT BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		FROM @TEMP
		GROUP BY BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		)
		,TABLE_T2
	AS (
		SELECT BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		FROM @TEMP
		WHERE DOCTYPE_P1 = DOCTYPE_P2
		GROUP BY BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		)
		,TABLE_T3
	AS (
		SELECT BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		FROM @TEMP
		WHERE DOCTYPE_P1 = DOCTYPE_P2
			AND DOC_CONF_P1 > conf_threshold_p1
		GROUP BY BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		)
		,TABLE_T4
	AS (
		SELECT BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		FROM @TEMP
		WHERE DOCTYPE_P1 = DOCTYPE_P2
				AND doctype1_pagecount = doctype2_pagecount
		GROUP BY BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		)
		,TABLE_T5
	AS (
		SELECT BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		FROM @TEMP
		WHERE DOCTYPE_P1 = DOCTYPE_P2
			AND DOC_CONF_P1 > conf_threshold_p1
				AND doctype1_pagecount = doctype2_pagecount
		GROUP BY BATCH_INSTANCEID
			,DOCID_P2
			,DOCTYPE_P2
		)
		,T1
	AS (
		SELECT DOCTYPE_P2
			,COUNT(1) DOCUMENTS_FOUND
		FROM TABLE_T1
		GROUP BY DOCTYPE_P2
		)
		,T2
	AS (
		SELECT DOCTYPE_P2
			,COUNT(1) CORRECT
		FROM TABLE_T2
		GROUP BY DOCTYPE_P2
		)
		,T3
	AS (
		SELECT DOCTYPE_P2
			,COUNT(1) CORRECT_CONFIDENT
		FROM TABLE_T3
		GROUP BY DOCTYPE_P2
		)
		,T4
	AS (
		SELECT DOCTYPE_P2
			,COUNT(1) CORRECT_W_PAGES
		FROM TABLE_T4
		GROUP BY DOCTYPE_P2
		)
		,T5
	AS (
		SELECT DOCTYPE_P2
			,COUNT(1) CORRECT_CONFIDENT_W_PAGES
		FROM TABLE_T5
		GROUP BY DOCTYPE_P2
		)
		,DOC_REPORT
	AS (
		SELECT T.DOCTYPE
			,ISNULL(T1.DOCUMENTS_FOUND, 0) AS TOTAL
			,ISNULL(T2.CORRECT, 0) AS CORRECT
			--,ISNULL(STR((CORRECT * 100.0 / DOCUMENTS_FOUND), 5, 2), 0.00) AS 'CORRECT_PERCENTAGE'
			,ISNULL(T3.CORRECT_CONFIDENT, 0) AS CORRECT_CONFIDENT
			,ISNULL(T4.CORRECT_W_PAGES, 0) AS CORRECT_W_PAGECOUNT
			,ISNULL(T5.CORRECT_CONFIDENT_W_PAGES, 0) AS CORRECT_CONFIDENT_W_PAGECOUNT
			--,ISNULL(STR((CORRECT_CONFIDENT * 100.0 / DOCUMENTS_FOUND), 5, 2), 0.00) AS 'CONFIDENT_PERCENTAGE'
		FROM @DOCUMENTTYPES T
		LEFT JOIN T1 ON T.DOCTYPE = T1.DOCTYPE_P2
		LEFT JOIN T2 ON T.DOCTYPE = T2.DOCTYPE_P2
		LEFT JOIN T3 ON T.DOCTYPE = T3.DOCTYPE_P2
		LEFT JOIN T4 ON T.DOCTYPE = T4.DOCTYPE_P2
		LEFT JOIN T5 ON T.DOCTYPE = T5.DOCTYPE_P2
		WHERE T.DOCTYPE IS NOT NULL
		)
	
	--SELECT * FROM DOC_REPORT
	SELECT @BatchId AS BATCH_INSTANCE_ID
			,CASE WHEN ISNULL(ROUND(SUM(CORRECT) * 100.0 / SUM(TOTAL), 5, 2), 0.00) > 90 THEN 
				ISNULL(STR(SUM(CORRECT_W_PAGECOUNT) * 100.0 / SUM(TOTAL), 5, 2), 0.00)
			ELSE ISNULL(STR(SUM(CORRECT) * 100.0 / SUM(TOTAL), 5, 2), 0.00)
			END 'BATCH_PERCENTAGE'
			--,ISNULL(ROUND(SUM(CORRECT) * 100.0 / SUM(TOTAL), 5, 2), 0.00)
			--,SUM(TOTAL)
			--,SUM(CORRECT)
			--,ISNULL(STR(SUM(CORRECT) * 100.0 / SUM(TOTAL), 5, 2), 0.00) AS 'CORRECT_PERCENTAGE'
			--,ISNULL(STR(SUM(CORRECT_W_PAGECOUNT) * 100.0 / SUM(TOTAL), 5, 2), 0.00) AS 'CORRECT_PERCENTAGE_W_PAGECOUNT'
			--,CAST(AVG(CAST(CORRECT_PERCENTAGE AS DECIMAL(6, 2))) AS DECIMAL(6, 2)) AS BATCH_PERCENTAGE
	FROM DOC_REPORT

	DROP TABLE #Doc_Count_p1
	DROP TABLE #Doc_Count_p2

END

