DECLARE @BATCHINSTANCEID VARCHAR(100) = '{BATCHINSTANCEID}';
DECLARE @BATCHCLASSID BIGINT = 0 ;
DECLARE @EPHESOFT_DOC_FIELD TABLE(DOCUMENT_NAME NVARCHAR(510), FIELD_NAME NVARCHAR(510));

SELECT @BATCHCLASSID = e.id FROM BATCHES b 
INNER JOIN Ephesoft.DBO.BATCH_CLASS e on b.batchclass_id = e.identifier 
where BATCH_INSTANCEID = @BATCHINSTANCEID

INSERT INTO @EPHESOFT_DOC_FIELD
select dm.document_type_name, field_type_name from Ephesoft.dbo.batch_class_document_type d
INNER JOIN ephesoft.dbo.field_type f on d.document_type_id = f.document_type_id
INNER JOIN ephesoft.dbo.document_type dm on d.document_type_id = dm.id where f.is_hidden = 0 and batch_class_id = @BATCHCLASSID


BEGIN
	DECLARE @TEMP TABLE (
		BATCH_INSTANCEID VARCHAR(50)
		,DOCID VARCHAR(50)
		,DOCTYPE VARCHAR(500)
		,FIELDNAME VARCHAR(MAX)
		,FIELDVALUE_P1 VARCHAR(MAX)
		,FIELDVALUE_P2 VARCHAR(MAX)
		);

	WITH MAINSELECT
	AS (
		SELECT E.BATCH_INSTANCEID
			,E.DOCID
			,E.DOCTYPE AS 'EDOCTYPE'
			,M.DOCTYPE AS 'MDOCTYPE'
			,E.FIELDNAME AS 'EFIELDNAME'
			,M.FIELDNAME AS 'MFIELDNAME'
			,ltrim(rtrim(replace(replace(replace(replace(replace(replace(E.FIELDVALUE, '$', ''), ',', ''), '.0000', ''), '.00', ''), '%', ''), '-', ''))) EFIELDVALUE
			,ltrim(rtrim(replace(replace(replace(replace(replace(replace(M.FIELDVALUE, '$', ''), ',', ''), '.0000', ''), '.00', ''), '%', ''), '-', ''))) MFIELDVALUE
		FROM FIELDS E WITH (NOLOCK)
		INNER JOIN FIELDS M WITH (NOLOCK) ON E.BATCH_INSTANCEID = M.BATCH_INSTANCEID
			AND E.DOCID = M.DOCID
		INNER JOIN BATCHES B WITH (NOLOCK) ON E.BATCH_INSTANCEID = B.BATCH_INSTANCEID

		INNER JOIN @EPHESOFT_DOC_FIELD EP ON E.DOCTYPE = EP.DOCUMENT_TYPE AND E.FIELDNAME = EP.FIELD_NAME
		INNER JOIN IntellaLend_IDC_Service.dbo.MTS_AUTO_VALIDATION_SKIP IDC WITH (NOLOCK) ON IDC.DOCUMENT_NAME = E.DOCTYPE

		WHERE E.BATCH_INSTANCEID = @BATCHINSTANCEID
			AND E.PATTERN LIKE '%AUTOMATED_VALIDATION%'
			AND M.PATTERN LIKE '%EXPORT%'
			AND B.STATUS = 'FINISHED'
		)
		,LOANAPPDOCS
	AS (
		SELECT BATCH_INSTANCEID
			,DOCID
			,EDOCTYPE AS 'DOCTYPE'
			,EFIELDNAME
			,EFIELDVALUE AS 'VALUE_1'
			,MFIELDVALUE AS 'VALUE_2'
		FROM MAINSELECT
		WHERE EFIELDNAME = MFIELDNAME
			AND MDOCTYPE = 'Loan Application 1003'
			AND (
				EDOCTYPE = 'Loan Application 1003 Format 1'
				OR EDOCTYPE = 'Loan Application 1003 Format 2'
				)
		)
		,ALLDOCS
	AS (
		SELECT BATCH_INSTANCEID
			,DOCID
			,EDOCTYPE AS 'DOCTYPE'
			,EFIELDNAME
			,EFIELDVALUE AS 'VALUE_1'
			,MFIELDVALUE AS 'VALUE_2'
		FROM MAINSELECT
		WHERE EDOCTYPE = MDOCTYPE
			AND EFIELDNAME = MFIELDNAME
		)
	-- INSERT DATA INTO TEMP TABLE
	INSERT INTO @TEMP
	SELECT BATCH_INSTANCEID
		,DOCID
		,DOCTYPE
		,EFIELDNAME
		,VALUE_1
		,VALUE_2
	FROM ALLDOCS
	
	UNION
	
	SELECT BATCH_INSTANCEID
		,DOCID
		,DOCTYPE
		,EFIELDNAME
		,VALUE_1
		,VALUE_2
	FROM LOANAPPDOCS

	DECLARE @DIST_TEMP TABLE (
		BATCH_INSTANCEID VARCHAR(100)
		,DOCID VARCHAR(50)
		,DOCTYPE VARCHAR(MAX)
		,TOTAL BIGINT
		);
	DECLARE @CORRECT_TEMP TABLE (
		BATCH_INSTANCEID VARCHAR(100)
		,DOCTYPE VARCHAR(MAX)
		,DOCID VARCHAR(50)
		,CORRECT BIGINT
		);

	INSERT INTO @DIST_TEMP
	SELECT BATCH_INSTANCEID
		,DOCID
		,DOCTYPE
		,COUNT(1) TOTAL
	FROM @TEMP T
	GROUP BY T.BATCH_INSTANCEID
		,T.DOCTYPE
		,T.DOCID

	INSERT INTO @CORRECT_TEMP
	SELECT T.BATCH_INSTANCEID
		,T.DOCTYPE
		,T.DOCID
		,COUNT(1) CORRECT
	FROM @TEMP T
	WHERE T.FIELDVALUE_P1 = T.FIELDVALUE_P2
	GROUP BY T.BATCH_INSTANCEID
		,T.DOCID
		,T.DOCTYPE

	SELECT T1.BATCH_INSTANCEID
		,SUM(T1.TOTAL) AS TOTAL
		,SUM(T3.CORRECT) AS CORRECT
		,ISNULL(STR((SUM(T3.CORRECT) * 100.0 / SUM(T1.TOTAL)), 5, 2), 0.00) AS BATCH_PERCENTAGE
	FROM @DIST_TEMP T1
	INNER JOIN EphesoftUtility2020.dbo.MTS_AUTO_VALIDATION_SKIP IDC WITH (NOLOCK) ON IDC.ConfigId = @BATCHCLASSCONFIGID
		AND IDC.DOCUMENT_NAME = T1.DOCTYPE
	LEFT JOIN @CORRECT_TEMP T3 ON T1.BATCH_INSTANCEID = T3.BATCH_INSTANCEID
		AND T1.DOCID = T3.DOCID
		AND T1.DOCTYPE = T3.DOCTYPE
	GROUP BY T1.BATCH_INSTANCEID
	ORDER BY 1

	SELECT T1.BATCH_INSTANCEID
		,T1.DOCID
		,T1.DOCTYPE
		,T1.TOTAL
		,T3.CORRECT
		,ISNULL(STR((T3.CORRECT * 100.0 / T1.TOTAL), 5, 2), 0.00) AS DOCUMENT_PERCENTAGE
	FROM @DIST_TEMP T1
	INNER JOIN EphesoftUtility2020.dbo.MTS_AUTO_VALIDATION_SKIP IDC WITH (NOLOCK) ON IDC.ConfigId = @BATCHCLASSCONFIGID
		AND IDC.DOCUMENT_NAME = T1.DOCTYPE
	LEFT JOIN @CORRECT_TEMP T3 ON T1.BATCH_INSTANCEID = T3.BATCH_INSTANCEID
		AND T1.DOCID = T3.DOCID
		AND T1.DOCTYPE = T3.DOCTYPE
	ORDER BY 1
		,2
		,3	

END
