package com.mts.idc.ephesoft.service;

public enum EphesoftModule {
	NONE,
	FOLDERIMPORT,
	PAGEPROCESS,
	DOCUMENTASSEMBLY,
	REVIEWDOCUMENT ,
	EXTRACTION,
	AUTOMATEDVALIDATION,
	FUNCTIONKEY ,
	VALIDATIONDOCUMENT,
	EXPORT
}
