DECLARE @FUNCTION_KEY VARCHAR(3) = 'F10';
DECLARE @METHOD_NAME VARCHAR(255) = 'markAllDocsAsValid';
DECLARE @METHOD_DESCRIPTION VARCHAR(255) = 'Mark All Documents Valid';
DECLARE @BATCH_CLASS_ID BIGINT = 27;
DECLARE @STARTINDEX BIGINT;

SELECT @STARTINDEX = MAX(ID)
FROM DBO.FUNCTION_KEY;

SET IDENTITY_INSERT [DBO].[FUNCTION_KEY] ON 

INSERT INTO [DBO].[FUNCTION_KEY] (
	[ID]
	,[CREATION_DATE]
	,[LAST_MODIFIED]
	,[IDENTIFIER]
	,[METHOD_NAME]
	,[SHORTCUT_KEY_NAME]
	,[UI_LABEL]
	,[DOCUMENT_TYPE_ID]
	)
SELECT @STARTINDEX + ROW_NUMBER() OVER (
		ORDER BY (
				SELECT DOCUMENT_TYPE_ID
				)
		)
	,GETDATE()
	,GETDATE()
	,'FK' + CONVERT(CHAR(18), CONVERT(BINARY (2), (
				@STARTINDEX + ROW_NUMBER() OVER (
					ORDER BY (
							SELECT DOCUMENT_TYPE_ID
							)
					)
				)), 2)
	,@METHOD_NAME
	,@FUNCTION_KEY
	,@METHOD_DESCRIPTION
	,DOCUMENT_TYPE_ID
FROM DBO.BATCH_CLASS_DOCUMENT_TYPE
WHERE BATCH_CLASS_ID = @BATCH_CLASS_ID

SET IDENTITY_INSERT [DBO].[FUNCTION_KEY] OFF 