DECLARE @DOCFILEDS VARCHAR(MAX) = 'Document Date';
DECLARE @DOCNAME VARCHAR(MAX) = 'Credit Supplements';


DECLARE @DOCIDCOUNT BIGINT;
DECLARE @DOCIDINDEX BIGINT = 1;
DECLARE @DOCIDTABLE TABLE(ID BIGINT,DOCUMENTTYPEID BIGINT);
DECLARE @CURRTDOCID BIGINT;

INSERT INTO @DOCIDTABLE
SELECT ROW_NUMBER() OVER (
		ORDER BY DocumentTypeID
		)
	,DocumentTypeID FROM [T1].DocumentTypeMasters WHERE Name = @DOCNAME

SELECT @DOCIDCOUNT = COUNT(1) FROM @DOCIDTABLE;

SET @DOCIDINDEX = 1;

--SELECT * FROM @DOCIDTABLE
DECLARE @DOCTABLE TABLE (		
Name VARCHAR(MAX),
DisplayName VARCHAR(MAX),
Active BIT,
CreatedOn DATETIME,
ModifiedOn DATETIME,
DocOrderByField VARCHAR(MAX),
AllowAccuracyCalc BIT,
IsDocName BIT
	);

	
INSERT INTO @DOCTABLE
SELECT data,data,1,GETDATE(),GETDATE(),NULL,0,0
FROM dbo.function_string_to_table(@DOCFILEDS, ',');

WHILE @DOCIDINDEX <= @DOCIDCOUNT
BEGIN

SELECT @CURRTDOCID = DocumentTypeID FROM @DOCIDTABLE WHERE ID =@DOCIDINDEX;

--SELECT @CURRTDOCID

INSERT INTO [T1].DocumentFieldMasters
SELECT 
@CURRTDOCID ,
Name ,
DisplayName ,
Active ,
CreatedOn ,
ModifiedOn ,
DocOrderByField ,
AllowAccuracyCalc,IsDocName FROM @DOCTABLE

SET @DOCIDINDEX = @DOCIDINDEX + 1;

END


