DECLARE @LOANTYPEID BIGINT = 11;
DECLARE @PARENTSTACKINGORDERID BIGINT = 120;

DECLARE @TEMPTABLE TABLE (
	ID BIGINT,
	CustomerID bigint,
	LoanTypeID bigint,
	StackingOrderID bigint
);
DECLARE @STACKINGORDERTABLE TABLE (
	DocumentTypeID bigint,
	DocumentTypeName nvarchar(max),
	SequencID bigint
);
DECLARE @CUSTDOCTABLE TABLE (
	ID BIGINT,
	DocumentTypeID bigint,
	DocumentTypeName nvarchar(max)
);

DELETE FROM @TEMPTABLE;
DELETE FROM @STACKINGORDERTABLE;

INSERT INTO @TEMPTABLE
select ROW_NUMBER() OVER(ORDER BY c.LoanTypeID), C.CustomerID, C.LoanTypeID,C.StackingOrderID from [t1].CustReviewLoanStackMapping c with(nolock)
where c.LoanTypeID = @LOANTYPEID  AND C.StackingOrderID <> @PARENTSTACKINGORDERID


INSERT INTO @STACKINGORDERTABLE
select S.DocumentTypeID, D.Name, S.SequenceID from [t1].StackingOrderDetailMasters S with(nolock)
INNER JOIN [T1].DocumentTypeMasters D WITH(NOLOCK) ON S.DocumentTypeID = D.DocumentTypeID
where S.StackingOrderID = @PARENTSTACKINGORDERID
ORDER BY S.SequenceID;

DECLARE @MAPPINGCOUNT BIGINT = 0;
DECLARE @MAPPINGINDEX BIGINT = 1;


DECLARE @CUSTOMERID BIGINT = 0;
DECLARE @STACKINGORDERID BIGINT = 0;

SELECT @MAPPINGCOUNT = COUNT(1) FROM @TEMPTABLE;

WHILE @MAPPINGINDEX <= @MAPPINGCOUNT
BEGIN

DELETE FROM @CUSTDOCTABLE;

SELECT @CUSTOMERID = CustomerID, @STACKINGORDERID = StackingOrderID FROM @TEMPTABLE WHERE ID = @MAPPINGINDEX;

INSERT INTO @CUSTDOCTABLE
SELECT ROW_NUMBER() OVER(PARTITION BY D.Name ORDER BY D.Name), D.DocumentTypeID, D.Name FROM [T1].CustLoanDocMapping C WITH(NOLOCK)
INNER JOIN [T1].DocumentTypeMasters D WITH(NOLOCK)  ON C.DocumentTypeID = D.DocumentTypeID
WHERE C.CustomerID = @CUSTOMERID AND C.LoanTypeID = @LOANTYPEID;

INSERT INTO [T1].StackingOrderDetailMasters
SELECT @STACKINGORDERID,C.DocumentTypeID, S.SequencID, 1, GETDATE(), GETDATE() AS STACKMAPPING FROM @STACKINGORDERTABLE S 
INNER JOIN @CUSTDOCTABLE C ON S.DocumentTypeName = C.DocumentTypeName
WHERE C.ID = 1;

SET @MAPPINGINDEX = @MAPPINGINDEX + 1;

END