USE [AgileMortgage]
GO

/****** Object:  Trigger [TR_T1_LOANS_FORINSERT]    Script Date: 7/16/2018 12:37:13 PM ******/
DROP TRIGGER [T1].[TR_T1_LOANS_FORINSERT]
GO

/****** Object:  Trigger [T1].[TR_T1_LOANS_FORINSERT]    Script Date: 7/16/2018 12:37:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [T1].[TR_T1_LOANS_FORINSERT] 
ON [T1].[Loans]
FOR INSERT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @LOANTYPEID INT
    SELECT  @LOANTYPEID = LOANTYPEID FROM INSERTED 
	IF(@LOANTYPEID=0)
	BEGIN
	  UPDATE [T1].LOANS
      SET LOANTYPEID = 2
      FROM INSERTED
      WHERE [T1].LOANS.LOANID = INSERTED.LOANID; 
	END
END
GO

ALTER TABLE [T1].[Loans] ENABLE TRIGGER [TR_T1_LOANS_FORINSERT]
GO


