DECLARE @DOCUMENTS VARCHAR(MAX) = 'Hazard Insurance Disclosure,Correspondent Loan Submission Form';
DECLARE @STACKINGORDERID BIGINT;
DECLARE @DOCTABLE TABLE (
	ID BIGINT
	,DocumentTypeName VARCHAR(max)
	);
DECLARE @LOANTYPETABLE TABLE (
	ID BIGINT
	,LoanTypeID BIGINT
	);

INSERT INTO @DOCTABLE
SELECT ROW_NUMBER() OVER (
		ORDER BY data
		)
	,data
FROM dbo.function_string_to_table(@DOCUMENTS, ',')

DECLARE @DOCCOUNT BIGINT = 1;
DECLARE @DOCROWCOUNT BIGINT;
DECLARE @LOANROWCOUNT BIGINT;

SELECT @DOCROWCOUNT = COUNT(1)
FROM @DOCTABLE;

DECLARE @MAXSEQUENCEID BIGINT;
DECLARE @CURRTILDOCID BIGINT;
DECLARE @LOANCOUNT BIGINT = 1;

INSERT INTO @LOANTYPETABLE
SELECT ROW_NUMBER() OVER (
		ORDER BY LoanTypeID
		)
	,LoanTypeID
FROM [IL].LoanTypeMasters

SELECT @LOANROWCOUNT = COUNT(1)
FROM @LOANTYPETABLE;

WHILE @DOCCOUNT <= @DOCROWCOUNT
BEGIN
	INSERT INTO [IL].DocumentTypeMasters
	SELECT DocumentTypeName
		,DocumentTypeName
		,1
		,GETDATE()
		,GETDATE()
		,0
	FROM @DOCTABLE
	WHERE ID = @DOCCOUNT

	SELECT @CURRTILDOCID = MAX(DocumentTypeID)
	FROM [IL].DocumentTypeMasters;

	--SELECT * FROM [IL].DocumentTypeMasters ORDER BY 1 DESC	
	SET @LOANCOUNT = 1;

	WHILE @LOANCOUNT <= @LOANROWCOUNT
	BEGIN
		SELECT @STACKINGORDERID = STACKINGORDERID
		FROM @LOANTYPETABLE L
		INNER JOIN [IL].CUSTREVIEWLOANSTACKMAPPING S ON S.LOANTYPEID = L.LoanTypeID
		WHERE CUSTOMERID = 1
			AND REVIEWTYPEID = 0
			AND L.ID = @LOANCOUNT

		IF @STACKINGORDERID > 0
		BEGIN
			SELECT @MAXSEQUENCEID = MAX(SequenceID)
			FROM [IL].StackingOrderDetailMasters
			WHERE StackingOrderID = @STACKINGORDERID

			INSERT INTO [IL].CustLoanDocMapping
			SELECT 1
				,LoanTypeID
				,@CURRTILDOCID
				,GETDATE()
				,GETDATE()
				,1
			FROM @LOANTYPETABLE
			WHERE ID = @LOANCOUNT

			INSERT INTO [IL].[STACKINGORDERDETAILMASTERS] (
				[STACKINGORDERID]
				,[DOCUMENTTYPEID]
				,[SEQUENCEID]
				,[ACTIVE]
				,[CREATEDON]
				,[MODIFIEDON]
				)
			SELECT @STACKINGORDERID
				,@CURRTILDOCID
				,@MAXSEQUENCEID + 1
				,1
				,GETDATE()
				,GETDATE()
		END

		SET @LOANCOUNT = @LOANCOUNT + 1;
	END

	SET @DOCCOUNT = @DOCCOUNT + 1;
END
