DECLARE @DOCUMENTS VARCHAR(MAX) = 'Hazard Insurance Disclosure,Correspondent Loan Submission Form';
DECLARE @CUSTOMER_COUNT BIGINT;
DECLARE @ROW_CUSTOMER_COUNT BIGINT = 1;
DECLARE @CUSTOMER TABLE (
	CustomerID BIGINT
	,ID BIGINT
	);
DECLARE @LOANTYPETABLE TABLE (
	ID BIGINT
	,LoanTypeID BIGINT
	);
DECLARE @REVIEWTYPETABLE TABLE (
	ID BIGINT
	,ReviewTypeID BIGINT
	);
DECLARE @LOANROWCOUNT BIGINT;
DECLARE @REVIEWROWCOUNT BIGINT;
DECLARE @DOCTABLE TABLE (
	ID BIGINT
	,DocumentTypeName VARCHAR(max)
	);
DECLARE @DOCCOUNT BIGINT = 1;
DECLARE @DOCROWCOUNT BIGINT;

SELECT @DOCROWCOUNT = COUNT(1)
FROM @DOCTABLE;

DECLARE @CURRTILDOCID BIGINT;

INSERT INTO @DOCTABLE
SELECT ROW_NUMBER() OVER (
		ORDER BY data
		)
	,data
FROM dbo.function_string_to_table(@DOCUMENTS, ',');

SELECT @DOCROWCOUNT = COUNT(1)
FROM @DOCTABLE;

WITH DIST_CUST
AS (
	SELECT DISTINCT CustomerID
	FROM [T1].CustLoanDocMapping
	)
INSERT INTO @CUSTOMER
SELECT CustomerID
	,ROW_NUMBER() OVER (
		ORDER BY CustomerID
		) AS ID
FROM DIST_CUST
ORDER BY CustomerID

SELECT @CUSTOMER_COUNT = COUNT(1)
FROM @CUSTOMER;

DECLARE @LOANCOUNT BIGINT = 1;
DECLARE @REVIEWROW BIGINT = 1;
DECLARE @STACKINGORDERID BIGINT;
DECLARE @MAXSEQUENCEID BIGINT;
DECLARE @CURRENT_CUSTID BIGINT;
DECLARE @CURRENT_LOANID BIGINT;

WHILE @ROW_CUSTOMER_COUNT <= @CUSTOMER_COUNT
BEGIN
	SELECT @CURRENT_CUSTID = CustomerID
	FROM @CUSTOMER
	WHERE ID = @ROW_CUSTOMER_COUNT

	SET @LOANCOUNT = 1;

	DELETE
	FROM @LOANTYPETABLE;

	WITH DIST_LOAN
	AS (
		SELECT DISTINCT LoanTypeID
		FROM [T1].CustLoanDocMapping
		WHERE CustomerID = @CURRENT_CUSTID
		)
	INSERT INTO @LOANTYPETABLE
	SELECT ROW_NUMBER() OVER (
			ORDER BY LoanTypeID
			)
		,LoanTypeID
	FROM DIST_LOAN

	SELECT @LOANROWCOUNT = COUNT(1)
	FROM @LOANTYPETABLE;

	SET @LOANCOUNT = 1;

	WHILE @LOANCOUNT <= @LOANROWCOUNT
	BEGIN
		SELECT @CURRENT_LOANID = LoanTypeID
		FROM @LOANTYPETABLE
		WHERE ID = @LOANCOUNT;

		SET @DOCCOUNT = 1;

		WHILE @DOCCOUNT <= @DOCROWCOUNT
		BEGIN
			INSERT INTO [T1].DocumentTypeMasters
			SELECT DocumentTypeName
				,DocumentTypeName
				,1
				,GETDATE()
				,GETDATE()
				,0
			FROM @DOCTABLE
			WHERE ID = @DOCCOUNT

			SELECT @CURRTILDOCID = MAX(DocumentTypeID)
			FROM [T1].DocumentTypeMasters;

			INSERT INTO [T1].CustLoanDocMapping
			SELECT @CURRENT_CUSTID
				,@CURRENT_LOANID
				,@CURRTILDOCID
				,GETDATE()
				,GETDATE()
				,1;

			DELETE
			FROM @REVIEWTYPETABLE;

			WITH DIST_REVIEW
			AS (
				SELECT DISTINCT ReviewTypeID
				FROM [T1].CustReviewLoanMapping
				WHERE CustomerID = @CURRENT_CUSTID
					AND LoanTypeID = @CURRENT_LOANID
				)
			INSERT INTO @REVIEWTYPETABLE
			SELECT ROW_NUMBER() OVER (
					ORDER BY ReviewTypeID
					)
				,ReviewTypeID
			FROM DIST_REVIEW

			SELECT @REVIEWROWCOUNT = COUNT(1)
			FROM @REVIEWTYPETABLE;

			SET @REVIEWROW = 1;

			WHILE @REVIEWROW <= @REVIEWROWCOUNT
			BEGIN
				SET @STACKINGORDERID = NULL;

				SELECT @STACKINGORDERID = STACKINGORDERID
				FROM @REVIEWTYPETABLE R
				INNER JOIN [T1].CUSTREVIEWLOANSTACKMAPPING S ON S.ReviewTypeID = R.ReviewTypeID
				WHERE CustomerID = @CURRENT_CUSTID
					AND LoanTypeID = @CURRENT_LOANID
					AND R.ID = @REVIEWROW

				IF @STACKINGORDERID IS NOT NULL
					AND @STACKINGORDERID > 0
				BEGIN
					SELECT @MAXSEQUENCEID = MAX(SequenceID)
					FROM [T1].StackingOrderDetailMasters
					WHERE StackingOrderID = @STACKINGORDERID

					IF @MAXSEQUENCEID IS NOT NULL
					BEGIN
						INSERT INTO [T1].[STACKINGORDERDETAILMASTERS] (
							[STACKINGORDERID]
							,[DOCUMENTTYPEID]
							,[SEQUENCEID]
							,[ACTIVE]
							,[CREATEDON]
							,[MODIFIEDON]
							)
						SELECT @STACKINGORDERID
							,@CURRTILDOCID
							,@MAXSEQUENCEID + 1
							,1
							,GETDATE()
							,GETDATE()
					END
				END

				SET @REVIEWROW = @REVIEWROW + 1;
			END

			SET @DOCCOUNT = @DOCCOUNT + 1;
		END

		SET @LOANCOUNT = @LOANCOUNT + 1;
	END

	SET @ROW_CUSTOMER_COUNT = @ROW_CUSTOMER_COUNT + 1;
END
