TRUNCATE TABLE [IL].AuditLoan
TRUNCATE TABLE [IL].AuditLoanDetails
TRUNCATE TABLE [IL].AuditLoanMissingDoc
TRUNCATE TABLE [IL].AuditLoanSearch
TRUNCATE TABLE [IL].BoxDownloadQueue
TRUNCATE TABLE [IL].CheckListDetailMasters
TRUNCATE TABLE [IL].CheckListMasters
TRUNCATE TABLE [IL].DocumentTypeMasters
TRUNCATE TABLE [IL].DocumentFieldMasters
TRUNCATE TABLE [IL].CustLoanDocMapping
TRUNCATE TABLE [IL].CustomerConfig
TRUNCATE TABLE [IL].CustReverificationDocMapping
TRUNCATE TABLE [IL].CustReviewLoanCheckMapping
TRUNCATE TABLE [IL].CustReviewLoanMapping
TRUNCATE TABLE [IL].CustReviewLoanStackMapping
TRUNCATE TABLE [IL].CustReviewLoanReverifyMapping
TRUNCATE TABLE [IL].CustReviewMapping
TRUNCATE TABLE [IL].EmailMaster
TRUNCATE TABLE [IL].LoanDetails
TRUNCATE TABLE [IL].LoanImages
TRUNCATE TABLE [IL].LoanPDF
TRUNCATE TABLE [IL].LoanReverification
TRUNCATE TABLE [IL].Loans
TRUNCATE TABLE [IL].LoanSearch
TRUNCATE TABLE [IL].PurgeStaging
TRUNCATE TABLE [IL].PurgeStagingDetails
TRUNCATE TABLE [IL].RuleMasters
TRUNCATE TABLE [IL].StackingOrderDetailMasters
TRUNCATE TABLE [IL].StackingOrderMasters
TRUNCATE TABLE [IL].ReverificationMasters

TRUNCATE TABLE [T1].ReverificationMasters
TRUNCATE TABLE [T1].AuditLoan
TRUNCATE TABLE [T1].AuditLoanDetails
TRUNCATE TABLE [T1].AuditLoanMissingDoc
TRUNCATE TABLE [T1].AuditLoanSearch
TRUNCATE TABLE [T1].BoxDownloadQueue
TRUNCATE TABLE [T1].DocumentTypeMasters
TRUNCATE TABLE [T1].DocumentFieldMasters
TRUNCATE TABLE [T1].CheckListDetailMasters
TRUNCATE TABLE [T1].CheckListMasters
TRUNCATE TABLE [T1].CustLoanDocMapping
TRUNCATE TABLE [T1].CustomerConfig
TRUNCATE TABLE [T1].CustReverificationDocMapping
TRUNCATE TABLE [T1].CustReviewLoanReverifyMapping
TRUNCATE TABLE [T1].CustReviewLoanCheckMapping
TRUNCATE TABLE [T1].CustReviewLoanMapping
TRUNCATE TABLE [T1].PurgeStagingDetails
TRUNCATE TABLE [T1].CustReviewLoanStackMapping
TRUNCATE TABLE [T1].CustReviewMapping
TRUNCATE TABLE [T1].LoanDetails
TRUNCATE TABLE [T1].LoanImages
TRUNCATE TABLE [T1].LoanPDF
TRUNCATE TABLE [T1].LoanReverification
TRUNCATE TABLE [T1].Loans
TRUNCATE TABLE [T1].LoanSearch
TRUNCATE TABLE [T1].PurgeStaging
TRUNCATE TABLE [T1].RuleMasters
TRUNCATE TABLE [T1].StackingOrderDetailMasters
TRUNCATE TABLE [T1].StackingOrderMasters
TRUNCATE TABLE [T1].ReviewTypeMasters
TRUNCATE TABLE [T1].[LoanTypeMasters]