/****** Object:  Table [dbo].[BATCHES]    Script Date: 09/13/2019 11:09:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCHES](
	[BATCH_ID] [int] IDENTITY(1,1) NOT NULL,
	[BATCH_INSTANCEID] [varchar](255) NOT NULL,
	[BATCH_NAME] [varchar](255) NULL,
	[CREATEDATE] [datetime] NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[BATCHCLASS_ID] [nvarchar](255) NULL,
	[BATCHCLASS_NAME] [nvarchar](max) NULL,
	[STATUS] [varchar](255) NULL,
	[REVIEW_OPERATOR] [nvarchar](255) NULL,
	[VALIDATION_OPERATOR] [nvarchar](255) NULL,
	[CLASSIFICATION_TYPE] [varchar](255) NULL,
 CONSTRAINT [PK_BATCHES] PRIMARY KEY CLUSTERED 
(
	[BATCH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CONFIGURATIONS]    Script Date: 09/13/2019 11:09:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIGURATIONS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[KEY] [nvarchar](255) NOT NULL,
	[VALUE] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_CONFIGURATIONS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[FIELDS]    Script Date: 09/13/2019 11:09:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FIELDS](
	[PK] [int] IDENTITY(1,1) NOT NULL,
	[DOCID] [nvarchar](255) NULL,
	[DOCTYPE] [nvarchar](255) NULL,
	[FIELDNAME] [nvarchar](255) NULL,
	[FIELDVALUE] [nvarchar](max) NULL,
	[BATCH_INSTANCEID] [varchar](255) NOT NULL,
	[PATTERN] [nvarchar](255) NULL,
 CONSTRAINT [PK_FIELDS] PRIMARY KEY CLUSTERED 
(
	[PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PAGES]    Script Date: 09/13/2019 11:09:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAGES](
	[PK] [int] IDENTITY(1,1) NOT NULL,
	[PAGEID] [nvarchar](255) NULL,
	[PAGE_CONFIDENCE] [decimal](18, 0) NULL,
	[LEARNED_FILENAME] [nvarchar](max) NULL,
	[PAGE_POSITION] [nvarchar](10) NULL,
	[DOCID] [nvarchar](255) NULL,
	[DOCTYPE] [nvarchar](255) NULL,
	[DOC_CONFIDENCE] [decimal](18, 0) NULL,
	[CONFIDENCE_THRESHOLD] [decimal](18, 0) NULL,
	[VALID] [bit] NULL,
	[REVIEWED] [bit] NULL,
	[BATCH_INSTANCEID] [nvarchar](255) NOT NULL,
	[PATTERN] [nvarchar](255) NULL,
 CONSTRAINT [PK_PAGES] PRIMARY KEY CLUSTERED 
(
	[PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  StoredProcedure [dbo].[DataExtractionSummary]    Script Date: 09/13/2019 11:09:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DataExtractionSummary]
(
	@STARTPATTERN VARCHAR(255),
	@ENDPATTERN VARCHAR(255),
	@BATCHCLASS varchar(5),
	@STARTDATE varchar(10),
	@ENDDATE varchar(10)
)
AS
BEGIN
DECLARE @TEMP TABLE 
(
 BATCH_INSTANCEID VARCHAR(50),
 DOCID VARCHAR(50),
 DOCTYPE VARCHAR(50),
 FIELDNAME VARCHAR(50),
 FIELDVALUE_P1 VARCHAR(255),
 FIELDVALUE_P2 VARCHAR(255)
)

-- INSERT DATA INTO TEMP TABLE
INSERT INTO @TEMP SELECT * FROM
(
	SELECT E.BATCH_INSTANCEID, E.DOCID, E.DOCTYPE, E.FIELDNAME, E.FIELDVALUE "VALUE_1", M.FIELDVALUE "VALUE_2"
    FROM FIELDS E, FIELDS M WHERE E.BATCH_INSTANCEID = M.BATCH_INSTANCEID AND 
    E.DOCID = M.DOCID AND E.DOCTYPE = M.DOCTYPE AND E.FIELDNAME = M.FIELDNAME
    AND E.PATTERN LIKE CONCAT('%',@STARTPATTERN,'%') AND M.PATTERN LIKE CONCAT('%',@ENDPATTERN,'%')
	AND E.BATCH_INSTANCEID IN (SELECT BATCH_INSTANCEID FROM BATCHES WHERE LASTMODIFIEDDATE BETWEEN @STARTDATE AND @ENDDATE AND BATCHCLASS_ID = @BATCHCLASS AND STATUS = 'FINISHED')
)T

/* FINAL QUERY */
-- QUERY
SELECT T1.DOCTYPE, T1.FIELDNAME, T2.TOTAL, T3.CORRECT, 
ISNULL(STR((T3.CORRECT * 100.0 / T2.TOTAL), 5, 2), 0.00) + '%' AS 'CORRECT%'
FROM
(
 (
  SELECT DISTINCT DOCTYPE, FIELDNAME FROM @TEMP
 ) T1
 LEFT JOIN
 (
  SELECT DOCTYPE, FIELDNAME, COUNT(1) TOTAL FROM @TEMP GROUP BY DOCTYPE, FIELDNAME
 ) T2 ON T1.DOCTYPE = T2.DOCTYPE AND T1.FIELDNAME = T2.FIELDNAME
 LEFT JOIN
 (
  SELECT DOCTYPE, FIELDNAME, COUNT(1) CORRECT FROM @TEMP 
  WHERE FIELDVALUE_P1 = FIELDVALUE_P2 GROUP BY DOCTYPE, FIELDNAME                  
 ) T3 ON T1.DOCTYPE = T3.DOCTYPE AND T1.FIELDNAME = T3.FIELDNAME
) ORDER BY T1.DOCTYPE, T1.FIELDNAME

END

GO
/****** Object:  StoredProcedure [dbo].[DocumentClassificationSummary]    Script Date: 09/13/2019 11:09:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DocumentClassificationSummary]
(
	@STARTPATTERN VARCHAR(255),
	@ENDPATTERN VARCHAR(255),
	@BATCHCLASS varchar(10),
	@STARTDATE varchar(10),
	@ENDDATE varchar(10)
)
AS
BEGIN
DECLARE @TEMP TABLE
(
 batch_instanceid varchar(150),
 docid_p1 varchar(150),
 docid_p2 varchar(150),
 doctype_p1 varchar(150) ,
 doctype_p2 varchar(150),
 doc_conf_p1 varchar(150),
 doc_conf_p2 varchar(150),
 conf_threshold_p1 varchar(150),
 conf_threshold_p2 varchar(150)
 --unique(batch_instanceid, doctype_p1, doctype_p2)
)

/*DECLARE @STARTDATE DATETIME
DECLARE @ENDDATE DATETIME
DECLARE @BATCHCLASS VARCHAR(9);

/*SET VARIABLES TO USE*/
SET @STARTDATE = '2014-01-01 00:00:00.000'
SET @ENDDATE = '2015-05-05 00:00:00.000' 
SET @BATCHCLASS = 'BC4E3F' */

INSERT INTO @TEMP 
SELECT * FROM
(
	/*SELECT E.BATCH_INSTANCEID, E.DOCID, M.DOCID "DOCID_AV", E.DOCTYPE, M.DOCTYPE "DOCTYPE_AV",
    E.DOC_CONFIDENCE, M.DOC_CONFIDENCE "DOC_CONFIDENCE_AV", E.CONFIDENCE_THRESHOLD, M.CONFIDENCE_THRESHOLD "CONFIDENCE_THRESHOLD_AV"
    FROM BATCHES B,PAGES E, PAGES M
    WHERE B.BATCH_INSTANCEID = E.BATCH_INSTANCEID AND E.BATCH_INSTANCEID = M.BATCH_INSTANCEID AND E.DOCID = M.DOCID AND
    B.LASTMODIFIEDDATE BETWEEN @STARTDATE AND @ENDDATE AND B.BATCHCLASS_ID = @BATCHCLASS AND B.STATUS = 'FINISHED'
    AND  E.PATTERN LIKE CONCAT('%',@STARTPATTERN,'%') AND M.PATTERN LIKE CONCAT('%',@ENDPATTERN,'%')*/

	SELECT E.BATCH_INSTANCEID, E.DOCID, M.DOCID "DOCID_AV", E.DOCTYPE, M.DOCTYPE "DOCTYPE_AV",
    E.DOC_CONFIDENCE, M.DOC_CONFIDENCE "DOC_CONFIDENCE_AV", E.CONFIDENCE_THRESHOLD, M.CONFIDENCE_THRESHOLD "CONFIDENCE_THRESHOLD_AV"
    FROM BATCHES B,PAGES E, PAGES M
    WHERE B.BATCH_INSTANCEID = E.BATCH_INSTANCEID  AND E.PAGEID = M.PAGEID AND B.BATCH_INSTANCEID = M.BATCH_INSTANCEID AND
    B.CREATEDATE BETWEEN @STARTDATE AND @ENDDATE AND B.BATCHCLASS_ID = @BATCHCLASS AND B.STATUS = 'FINISHED'
    AND  E.PATTERN LIKE CONCAT('%',@STARTPATTERN,'%') AND M.PATTERN LIKE CONCAT('%',@ENDPATTERN,'%')
) T

--SELECT * FROM @TEMP order by batch_instanceid, docid_p1

/* FINAL QUERY */
SELECT T.DOCTYPE, 
ISNULL(T1.DOCUMENTS_FOUND, 0) AS TOTAL, 
ISNULL(T2.CORRECT, 0) AS CORRECT, 
ISNULL(STR((CORRECT * 100.0/DOCUMENTS_FOUND), 5, 2), 0.00)+'%' AS 'CORRECT%',
ISNULL(T3.CORRECT_CONFIDENT, 0) AS CORRECT_CONFIDENT,
ISNULL(STR((CORRECT_CONFIDENT * 100.0/DOCUMENTS_FOUND), 5, 2), 0.00)+'%' AS 'CORRECT_CONFIDENT%'
FROM
(
	SELECT DISTINCT DOCTYPE FROM BATCHES B, PAGES P
	WHERE B.BATCH_INSTANCEID = P.BATCH_INSTANCEID AND B.BATCHCLASS_ID = @BATCHCLASS
) T  
LEFT JOIN
(
 SELECT DOCTYPE_P2, COUNT(1) DOCUMENTS_FOUND FROM 
 (
  SELECT BATCH_INSTANCEID, DOCID_P2, DOCTYPE_P2 
  FROM @TEMP
  GROUP BY BATCH_INSTANCEID, DOCID_P2, DOCTYPE_P2
 ) T GROUP BY DOCTYPE_P2
) T1 ON T.DOCTYPE = T1.DOCTYPE_P2
LEFT JOIN
(
 SELECT DOCTYPE_P2, COUNT(1) CORRECT FROM
 (
   SELECT BATCH_INSTANCEID, DOCID_P2, DOCTYPE_P2
   FROM @TEMP
   WHERE DOCTYPE_P1 = DOCTYPE_P2
   GROUP BY BATCH_INSTANCEID, DOCID_P2, DOCTYPE_P2
 ) T GROUP BY DOCTYPE_P2
) T2 ON T.DOCTYPE = T2.DOCTYPE_P2 
LEFT JOIN
(
 SELECT DOCTYPE_P2, COUNT(1) CORRECT_CONFIDENT FROM 
 (
  SELECT BATCH_INSTANCEID, DOCID_P2, DOCTYPE_P2
  FROM @TEMP
  WHERE DOCTYPE_P1 = DOCTYPE_P2 AND DOC_CONF_P1 > conf_threshold_p1   -- CLASSIFIED CORRECTLY WITH HIGH CONFIDENCE
  GROUP BY BATCH_INSTANCEID, DOCID_P2, DOCTYPE_P2
 ) T GROUP BY DOCTYPE_P2
) T3 ON T.DOCTYPE = T3.DOCTYPE_P2
WHERE T.DOCTYPE IS NOT NULL
ORDER BY T.DOCTYPE
END

GO
/****** Object:  StoredProcedure [dbo].[PageClassificationSummary]    Script Date: 09/13/2019 11:09:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PageClassificationSummary]
(
	@STARTPATTERN VARCHAR(255),
	@ENDPATTERN VARCHAR(255),
	@BATCHCLASS varchar(5),
	@STARTDATE datetime,
	@ENDDATE datetime
)
AS

BEGIN

SET NOCOUNT ON;

DECLARE @TEMP TABLE
(
	batch_instanceid varchar(150),
	docid_p1 varchar(10),
	docid_p2 varchar(10),
	pageid_p1 varchar(10),
	pageid_p2 varchar(10),
	doctype_p1 varchar(150),
	doctype_p2 varchar(150),
	page_conf_p1 varchar(10),
	page_conf_p2 varchar(10),
	threshold_p1 varchar(10),
	threshold_p2 varchar(10),
	position_p1 varchar(10),
	position_p2 varchar(10),
	pattern_p1 varchar(255),
	pattern_p2 varchar(255)
)

INSERT INTO @TEMP 
SELECT * FROM
(
	/* SELECT E.BATCH_INSTANCEID, E.DOCID "DOCID_BR", M.DOCID "DOCID_AR", E.PAGEID "PAGEID_BR", M.PAGEID "PAGEID_AR", E.DOCTYPE "DocType_BR", M.DOCTYPE "DOCTYPE_AR",
    E.PAGE_CONFIDENCE "CONFIDENCE_BR", M.PAGE_CONFIDENCE "CONFIDENCE_AR", E.CONFIDENCE_THRESHOLD "THRESHOLD_BR", M.CONFIDENCE_THRESHOLD "THRESHOLD_AR",
    E.PAGE_POSITION "POSITION_BR", M.PAGE_POSITION "POSITION_AR", E.PATTERN "PATTERN_BR", M.PATTERN "PATTERN_AR" FROM BATCHES B,PAGES E, PAGES M  
	WHERE B.BATCH_INSTANCEID = E.BATCH_INSTANCEID AND B.BATCH_INSTANCEID = M.BATCH_INSTANCEID AND E.BATCH_INSTANCEID = M.BATCH_INSTANCEID AND 
	E.DOCID = M.DOCID AND E.DOCTYPE = M.DOCTYPE AND E.PAGEID = M.PAGEID AND B.LASTMODIFIEDDATE BETWEEN @STARTDATE AND @ENDDATE
	AND B.BATCHCLASS_ID = @BATCHCLASS AND B.STATUS = 'FINISHED' AND  E.PATTERN LIKE CONCAT('%',@STARTPATTERN,'%') AND M.PATTERN LIKE CONCAT('%',@ENDPATTERN,'%') */

	SELECT E.BATCH_INSTANCEID, E.DOCID "DOCID_BR", M.DOCID "DOCID_AR", E.PAGEID "PAGEID_BR", M.PAGEID "PAGEID_AR", E.DOCTYPE "DocType_BR", M.DOCTYPE "DOCTYPE_AR",
    E.PAGE_CONFIDENCE "CONFIDENCE_BR", M.PAGE_CONFIDENCE "CONFIDENCE_AR", E.CONFIDENCE_THRESHOLD "THRESHOLD_BR", M.CONFIDENCE_THRESHOLD "THRESHOLD_AR",
    E.PAGE_POSITION "POSITION_BR", M.PAGE_POSITION "POSITION_AR", E.PATTERN "PATTERN_BR", M.PATTERN "PATTERN_AR" FROM BATCHES B,PAGES E, PAGES M  
	WHERE B.BATCH_INSTANCEID = E.BATCH_INSTANCEID AND B.BATCH_INSTANCEID = M.BATCH_INSTANCEID AND E.PAGEID = M.PAGEID AND B.CREATEDATE BETWEEN @STARTDATE AND @ENDDATE
	AND B.BATCHCLASS_ID = @BATCHCLASS AND B.STATUS = 'FINISHED' AND  E.PATTERN LIKE CONCAT('%',@STARTPATTERN,'%') AND M.PATTERN LIKE CONCAT('%',@ENDPATTERN,'%')
) T

--SELECT * FROM @TEMP order by batch_instanceid, pageid_p1 

SELECT T.DOCTYPE, 
ISNULL(T1.PAGES_FOUND_BEFORE, 0) AS PAGES_FOUND_BEFORE, 
ISNULL(T2.PAGES_FOUND_AFTER, 0) AS PAGES_FOUND_AFTER,
ISNULL(T3.CORRECT, 0) AS CORRECT, 
ISNULL(STR((CORRECT * 100.0/PAGES_FOUND_AFTER), 5, 2), 0.00)+'%' AS 'CORRECT%',
ISNULL(T4.CORRECT_CONFIDENT, 0) AS CORRECT_CONFIDENT, 
ISNULL(STR((CORRECT_CONFIDENT * 100.0/PAGES_FOUND_AFTER), 5, 2), 0.00)+'%' AS 'CORRECT_CONFIDENT%',
ISNULL(T5.FALSE_POSITIVE, 0) AS FALSE_POSITIVE,
ISNULL(STR((FALSE_POSITIVE * 100.0/PAGES_FOUND_BEFORE), 5, 2), 0.00)+'%' AS 'FALSE_POSITIVE%',
ISNULL(T6.FALSE_NEGATIVE, 0) AS FALSE_NEGATIVE,
ISNULL(STR((FALSE_NEGATIVE * 100.0/PAGES_FOUND_AFTER), 5, 2), 0.00)+'%' AS 'FALSE_NEGATIVE%',
ISNULL(T7.MERGE_COUNT, 0) AS MERGE_COUNT,
ISNULL(STR((MERGE_COUNT * 100.0/PAGES_FOUND_AFTER), 5, 2), 0.00)+'%' AS 'MERGE_COUNT%',
ISNULL(T8.SPLIT_COUNT, 0) AS SPLIT_COUNT,
ISNULL(STR((SPLIT_COUNT * 100.0/PAGES_FOUND_AFTER), 5, 2), 0.00)+'%' AS 'SPLIT_COUNT%',
ISNULL(T9.CLASSIFICATION_CHANGE, 0) AS CLASSIFICATION_CHANGE,
ISNULL(STR((CLASSIFICATION_CHANGE * 100.0/PAGES_FOUND_AFTER), 5, 2), 0.00)+'%' AS 'CLASSIFICATION_CHANGE%'
FROM 
(
	SELECT DISTINCT DOCTYPE FROM BATCHES B WITH(NOLOCK), PAGES P WITH(NOLOCK)
	WHERE B.BATCH_INSTANCEID = P.BATCH_INSTANCEID AND B.BATCHCLASS_ID = @BATCHCLASS
) T

LEFT JOIN
(
 SELECT DOCTYPE_P1, COUNT(1) PAGES_FOUND_BEFORE
 FROM @TEMP GROUP BY DOCTYPE_P1
) T1 ON T.DOCTYPE = T1.DOCTYPE_P1 

LEFT JOIN
(
 SELECT DOCTYPE_P2, COUNT(1) PAGES_FOUND_AFTER
 FROM @TEMP GROUP BY DOCTYPE_P2
) T2 ON T.DOCTYPE = T2.DOCTYPE_P2

LEFT JOIN
(
  SELECT DOCTYPE_P2, COUNT(1) CORRECT
  FROM @TEMP
  WHERE DOCTYPE_P2 = DOCTYPE_P1
  GROUP BY DOCTYPE_P2 
) T3 ON T.DOCTYPE = T3.DOCTYPE_P2

LEFT JOIN
(
 SELECT DOCTYPE_P2, COUNT(1) CORRECT_CONFIDENT FROM
 (
  SELECT DOCTYPE_P2, PAGE_CONF_P1, THRESHOLD_P2
  FROM @TEMP WHERE DOCTYPE_P2 = DOCTYPE_P1 AND PAGE_CONF_P1> THRESHOLD_P2
 ) T4_1 GROUP BY DOCTYPE_P2
) T4 ON T.DOCTYPE = T4.DOCTYPE_P2

LEFT JOIN
(
 SELECT DOCTYPE_P1, COUNT(1) FALSE_POSITIVE FROM
 (
  SELECT DOCTYPE_P1, DOCTYPE_P2, PAGE_CONF_P1, THRESHOLD_P2 
  FROM @TEMP
  WHERE DOCTYPE_P1 != DOCTYPE_P2 AND PAGE_CONF_P1 > THRESHOLD_P2
 ) T5_1 GROUP BY DOCTYPE_P1
) T5 ON T.DOCTYPE = T5.DOCTYPE_P1

LEFT JOIN
(
 SELECT DOCTYPE_P2, COUNT(1) FALSE_NEGATIVE FROM
 (
  SELECT DOCTYPE_P1, DOCTYPE_P2, PAGE_CONF_P1, THRESHOLD_P2
  FROM @TEMP
  WHERE DOCTYPE_P1 != DOCTYPE_P2 AND PAGE_CONF_P1 > THRESHOLD_P2
 ) T6_1 GROUP BY DOCTYPE_P2 
) T6 ON T.DOCTYPE = T6.DOCTYPE_P2

LEFT JOIN
(
 SELECT DOCTYPE_P2, COUNT(1) MERGE_COUNT FROM     --wrong document separation , no of pages merged
 (
  SELECT BATCH_INSTANCEID, DOCID_P1, DOCID_P2, DOCTYPE_P1, DOCTYPE_P2, PAGE_CONF_P1, PAGE_CONF_P2, 
  THRESHOLD_P1, THRESHOLD_P2,POSITION_P1, POSITION_P2 
  FROM @TEMP
  WHERE POSITION_P1 = 'FIRST' AND POSITION_P2 != 'FIRST'
 ) T7_1 GROUP BY DOCTYPE_P2
) T7 ON T.DOCTYPE = T7.DOCTYPE_P2 

LEFT JOIN
(
 SELECT DOCTYPE_P2, COUNT(1) SPLIT_COUNT FROM      --no of page ssplit, for every split we are creating new document
 (
  SELECT BATCH_INSTANCEID, DOCID_P1, DOCID_P2, DOCTYPE_P1, DOCTYPE_P2, PAGE_CONF_P1, PAGE_CONF_P2, 
  THRESHOLD_P1, THRESHOLD_P2,POSITION_P1, POSITION_P2
  FROM @TEMP
  WHERE ((POSITION_P1 = 'MIDDLE' OR POSITION_P1 = 'LAST') AND (POSITION_P2 = 'FIRST'))
 ) T8_1 GROUP BY DOCTYPE_P2
) T8 ON T.DOCTYPE = T8.DOCTYPE_P2 

LEFT JOIN
(
 SELECT DOCTYPE_P2, COUNT(1) CLASSIFICATION_CHANGE FROM
 (
  SELECT BATCH_INSTANCEID, DOCID_P1, DOCID_P2, DOCTYPE_P1, DOCTYPE_P2, PAGE_CONF_P1, PAGE_CONF_P2, 
  THRESHOLD_P1, THRESHOLD_P2, POSITION_P1, POSITION_P2 
  FROM @TEMP
  WHERE DOCTYPE_P1 != DOCTYPE_P2 AND DOCID_P1 = DOCID_P2
 ) T9_1 GROUP BY DOCTYPE_P2
) T9 ON T.DOCTYPE = T9.DOCTYPE_P2 
WHERE T.DOCTYPE IS NOT NULL
ORDER BY T.DOCTYPE
END

GO
